apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- backup-cronjob.yaml
images:
- name: PROJECT/IMAGE_DIR1
  newName: europe-north1-docker.pkg.dev/dwk-gke-467121/my-repository/todo-app
  newTag: 4.9-a6d891a296a02257c365c2a1c17a1634f7838548
- name: PROJECT/IMAGE_DIR2
  newName: europe-north1-docker.pkg.dev/dwk-gke-467121/my-repository/todo-backend
  newTag: 4.9-a6d891a296a02257c365c2a1c17a1634f7838548
