apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-list-cj
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-cron
            image: python:3.12
            imagePullPolicy: IfNotPresent
            command: ["sh", "-c"]
            args:
            - |
              pip install requests && \
              python3 -c "import requests;requests.post('http://todo-list-svc:4040/todos', data={'todo-input': 'Read ' + str(requests.get('https://en.wikipedia.org/wiki/Special:Random').url)})"
          restartPolicy: Never

