apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- persistentvolumeclaim.yaml
- statefulset.yaml
- secret.yaml
- configmaps.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- cronjob.yaml
