apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-list-claim # name of the volume claim, this will be used in the deployment
spec:
  storageClassName: standard-rwo # this is the name of the persistent volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
